In [1]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a[0,1], a[1,2], a[0,2])

2 6 3


In [2]:
import numpy as np 

a = np.array([[10, 11, 12]])
b = np.array([[20], [21], [22]])
c = np.array([[1,2], [3,4], [5,6]])
print(a.shape, b.shape, c.shape)


(1, 3) (3, 1) (3, 2)


In [3]:
import numpy as np 
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I


In [5]:
x


array([[1., 0.],
       [0., 0.]])

In [6]:
y

matrix([[1., 1.],
        [2., 0.]])

In [8]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a[0] = a[0,::-1]
a[:,1]=a[::-1,1]

In [9]:
a

array([[ 5,  7,  3,  2,  1],
       [ 6,  4,  8,  9, 10]])

In [10]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
b = a.T
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
import numpy as np
a = np.array([1,2, 3, []]) 
a[-1].append(4)
a[-1].append(5)
print(len(a))

4


In [12]:
import numpy as np 
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I

In [14]:
x

array([[1., 0.],
       [0., 0.]])

In [16]:
y

matrix([[1., 1.],
        [2., 0.]])

In [17]:
import numpy as np 
a = np.zeros((2,2))
b = np.eye(2)

In [18]:
a

array([[0., 0.],
       [0., 0.]])

In [19]:
b

array([[1., 0.],
       [0., 1.]])

In [20]:
import numpy as np 

b = np.mat([[5, 6], [7, 8]])

In [22]:
print(type(b))

<class 'numpy.matrix'>


In [23]:
import numpy as np 
a = np.ones(2)
b = np.ones((1,2))


In [24]:
a

array([1., 1.])

In [25]:
b

array([[1., 1.]])

In [26]:
print(a,b)

[1. 1.] [[1. 1.]]


In [27]:
import numpy as np
a = np.array( [[1,2, 3, 4],  [5,6, 7, 8],  [9,10,11,12]] )
b = a[1:3, 2:]
b

array([[ 7,  8],
       [11, 12]])

In [28]:
import numpy as np
a = np.array([[1,2], [3,4]])
#A list comprehension 
b = [a[j,i] for i in range(a.shape[0]) for j in range(a.shape[1])]
b

[1, 3, 2, 4]

In [29]:
import numpy as np
a = np.array([[1,2], [3,4]])
#A list comprehension 
b = [a[j,i] for i in range(a.shape[0]) for j in range(a.shape[1])]

In [31]:
b

[1, 3, 2, 4]

In [32]:
import numpy as np 
a = np.array([[1, 0], [2, -1]])
r = a * a
r

array([[1, 0],
       [4, 1]])

In [33]:
import numpy as np 
a = np.matrix([[1, 0], [2, -1]])
r = a * a

In [34]:
r

matrix([[1, 0],
        [0, 1]])

In [35]:
import numpy as np 
a = np.zeros((2,2))
b = np.eye(2)
a

array([[0., 0.],
       [0., 0.]])

In [36]:
b

array([[1., 0.],
       [0., 1.]])

In [37]:
import numpy as np 
a = np.zeros((2,2))
b = np.eye(2)
a

array([[0., 0.],
       [0., 0.]])

In [38]:
b


array([[1., 0.],
       [0., 1.]])