# Joshua Chavez
## Week 11 -   3/26/24 
### Python numpy procesing Arrays

In [1]:
import numpy as np

In [2]:
lst = [11,22,33,44,55,66,77]

In [3]:
lst

[11, 22, 33, 44, 55, 66, 77]

In [4]:
arr = np.array(lst)

In [5]:
arr

array([11, 22, 33, 44, 55, 66, 77])

In [6]:
arr.dtype

dtype('int32')

In [7]:
# createing an array from a nested list
lst1 =[ [1,2,3,4,5],[11,22,33,44,55]]

In [8]:
arr = np.array(lst)
arr

array([11, 22, 33, 44, 55, 66, 77])

In [9]:
arr.ndim

1

In [10]:
arr.shape


(7,)

In [11]:
arr.dtype

dtype('int32')

In [12]:
arr = np.array(['Orange', ' Appple', "Cherry", 'Grape'])

In [13]:
arr

array(['Orange', ' Appple', 'Cherry', 'Grape'], dtype='<U7')

In [14]:
arr.dtype

dtype('<U7')

In [15]:
arr = np.array(['Orange', ' Appple', "Cherry", 'Grape', 1,2,3,4,5,[6,7,8,9,10],(10,11,12)])
arr

array(['Orange', ' Appple', 'Cherry', 'Grape', 1, 2, 3, 4, 5,
       list([6, 7, 8, 9, 10]), (10, 11, 12)], dtype=object)

In [16]:
arr.dtype

dtype('O')

In [18]:
#convert Data Types.
arr =np.array([10,11,12,13,14,15],dtype = "S")
arr

array([b'10', b'11', b'12', b'13', b'14', b'15'], dtype='|S2')

In [19]:
arr.dtype

dtype('S2')

In [20]:
arr = np.array([1,2,3,4,5],dtype = 'i8')

In [21]:
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [25]:
arr.dtype

dtype('int64')

In [26]:
arr = np.array([78.5,88.9,90.3,89.9])
arr

array([78.5, 88.9, 90.3, 89.9])

In [27]:
arr_int = arr.astype('i')
arr_int

array([78, 88, 90, 89], dtype=int32)

In [29]:
arr= np.array([1,0,0,1,2,0,1,2,1,2,3,0])

In [34]:
#numPy array copy, view, AND ASSIGMENT (=)
#COPY
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
arr_copy= arr.copy()
arr_copy


array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
arr[0]= 10
arr

array([10,  2,  3,  4,  5,  6,  7,  8])

In [38]:
arr_copy

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [41]:
arr_view = arr.view()

In [42]:
arr_view

array([1, 2, 3, 4, 5])

In [43]:
arr[-1]=99

In [44]:
arr

array([ 1,  2,  3,  4, 99])

In [46]:
arr_view

array([ 1,  2,  3,  4, 99])

In [47]:
#assigment = 
arr = np.array([1,2,3,4,5])

In [48]:
arr_assign= arr
arr_assign

array([1, 2, 3, 4, 5])

In [51]:
print(arr.base)
print(arr_copy.base)
print(arr_view.base)
print(arr_assign.base)

None
None
[ 1  2  3  4 99]
None


In [52]:
#shape give you nuum of elemnets in each dimesion
lst1 = [1,2,3,4,5]
lst2 = [11,12,13,14,15]

In [53]:
lst = [lst1,lst2]

In [54]:
arr = lst.array()

AttributeError: 'list' object has no attribute 'array'

In [56]:
# Writing data to file
f = open("data.txt", 'w')
f.write("1,2,3\n")
f.write("4,5,6")
f.close()

# Reading data from file
r = open("data.txt", 'r')
print(r.read())
r.close()


1,2,3
4,5,6


In [57]:

# Using np.genfromtxt
arr = np.genfromtxt('data.txt', dtype=None)

# Print the array
print(arr)


[b'1,2,3' b'4,5,6']


c:\Miniconda\envs\py37_default\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


In [60]:
# Using np.loadtxt
arr = np.loadtxt("data1.txt", dtype='i8')

# Print the array
print(arr)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [61]:
arr.ndim

2

In [62]:
arr.shape

(5, 2)

In [63]:
# zeros 
#return nre array of given shape and type filled with  zeros

In [64]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [66]:
arr =np.zeros([5,5])

In [67]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [68]:
arr.shape

(5, 5)

In [69]:
arr = np.zeros((5,3,3,2))

In [70]:
arr

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [71]:
arr.shape

(5, 3, 3, 2)

In [72]:
# ones 
#return nre array of given shape and type filled with  ones
arr = np.ones((5,5),dtype = int)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [73]:
arr = np.ones((3,4,4,5))

In [74]:
arr

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1

In [75]:
arr.shape

(3, 4, 4, 5)

In [76]:
arr = np.empty((5,5),dtype = int)
arr

array([[       1180,           0,           4,           0,         952],
       [          0,         411,           0,         956,           0],
       [        411,           0,         968,           0,  -833038906],
       [-2147482369,         788,           0,         411,    24313855],
       [        988,           0,         411,          -1,        1032]])

In [77]:
arr = np.empty((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [80]:
arr = np.arange(10,100,5)
arr


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [81]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
#reshape an array 
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [83]:
arr_2d = arr.reshape(3,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
arr_2d.shape

(3, 4)

In [85]:
arr_2d = arr.reshape(2,2,3)
arr_2d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [87]:
arr = np.arange(1,16).reshape(5,3)

In [88]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [89]:
arr.base

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [90]:
arr_2d.base

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [96]:
arr_2d[0]= 100
arr_2d

array([[[100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [ 10,  11,  12]]])