# Joshua Chavez
## Week 11 -   3/26/24 
### Python numpy intro

- NumPy is a python libray
- NumPy is used for working with arrays
- NumPy is is short for Numerical Python
- NumPy is 50x faster than traditonal Py list 
- are stored at one comtinuous place in memory.
- The array object is NumPy is called ndArray 

In [2]:
import numpy as np

In [3]:
np.__version__

'1.18.5'

In [4]:
# create am NumPy ndarray Object
arr = np.array([1,2,3,4,5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.ndim

1

In [7]:
#dimensions in Arrays 
# a dimension in Arrays is ome level of array depth (nested arrays).

In [8]:
arr_0d = np.array(50)
arr_0d

array(50)

In [9]:
arr_0d.ndim

0

In [10]:
#1-D array
arr_1d = np.array([1,23,34,2,12])

In [11]:
arr_1d.ndim

1

In [13]:
#2-D array 
arr_2d = np.array([[1,23,34],[2,3,2],[21,32,12]])

In [14]:
arr_2d.ndim

2

In [15]:
arr_2d.shape

(3, 3)

In [16]:
# in a 3- D array it must have 2 d as its elemensts 

In [20]:
arr_3d = np.array( [ [  [1,23,34],[2,3,2],[21,32,12]],[  [1,23,34],[2,3,2],[21,32,12]] ] )

In [21]:
arr_3d.ndim

3

In [22]:
arr_3d.shape

(2, 3, 3)

In [33]:
arr_4d 

NameError: name 'arr_4d' is not defined

In [36]:
#create 4 d array+
arr_4d= np.array( [[ [  [  1,2,4,4]]]])

In [37]:
arr_4d.ndim

4

In [38]:
arr_4d.shape

(1, 1, 1, 4)

In [39]:
#acess 1-D array 
#array indexting
arr_1d[-1]

12

In [40]:
arr_1d[2]

34

In [41]:
arr_1d[0]+ arr_1d[-1]

13

In [42]:
#acessing 2-D array
arr_2d

array([[[ 1, 23, 34],
        [ 2,  3,  2],
        [21, 32, 12]],

       [[ 1, 23, 34],
        [ 2,  3,  2],
        [21, 32, 12]]])

In [43]:
arr_2d[0]

array([[ 1, 23, 34],
       [ 2,  3,  2],
       [21, 32, 12]])

In [44]:
arr_2d[1]

array([[ 1, 23, 34],
       [ 2,  3,  2],
       [21, 32, 12]])

In [48]:
arr_2d[1,2,2]

12

In [49]:
arr_2d[1,2,1]

32

In [53]:
arr_2d[0,2,0]

21

In [52]:
arr_2d.ndim

3

In [56]:
# sliceing np arrays
#[start:end:step]
# 1-d array
arr([1,2,3,4,5,6,7])

TypeError: 'numpy.ndarray' object is not callable

In [57]:
# Create a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Slice the array from index 1 to index 5 with a step of 2
sliced_array = arr[1:6:2]

print(sliced_array)



[2 4 6]


In [58]:
arr[1:5:2]

array([2, 4])

In [62]:
arr_2d[:]

array([[[ 1, 23, 34],
        [ 2,  3,  2],
        [21, 32, 12]],

       [[ 1, 23, 34],
        [ 2,  3,  2],
        [21, 32, 12]]])

In [63]:
arr_2d[1:]

array([[[ 1, 23, 34],
        [ 2,  3,  2],
        [21, 32, 12]]])

In [69]:
arr_2d[0:-1]

array([[[ 1, 23, 34],
        [ 2,  3,  2],
        [21, 32, 12]]])

In [72]:
arr_2d[0, 0:1]

array([[ 1, 23, 34]])

In [75]:
arr_2d[:]

array([[[ 1, 23, 34],
        [ 2,  3,  2],
        [21, 32, 12]],

       [[ 1, 23, 34],
        [ 2,  3,  2],
        [21, 32, 12]]])

In [77]:
arr_2d[1:]

array([[[ 1, 23, 34],
        [ 2,  3,  2],
        [21, 32, 12]]])

In [81]:
arr_2d[:,:2,:1]

array([[[1],
        [2]],

       [[1],
        [2]]])

In [82]:
arr_2d.shape

(2, 3, 3)

In [102]:
arr_2d[:]

array([[[ 1, 23, 34],
        [ 2,  3,  2],
        [21, 32, 12]],

       [[ 1, 23, 34],
        [ 2,  3,  2],
        [21, 32, 12]]])

In [84]:
arr_2d[:1]

array([[[ 1, 23, 34],
        [ 2,  3,  2],
        [21, 32, 12]]])

In [86]:
arr_2d[1:]

array([[[ 1, 23, 34],
        [ 2,  3,  2],
        [21, 32, 12]]])

In [87]:
arr_2d[:1,:]

array([[[ 1, 23, 34],
        [ 2,  3,  2],
        [21, 32, 12]]])

In [88]:
arr_2d[:1,0]

array([[ 1, 23, 34]])

In [101]:
arr_2d[0,:,0:2]

array([[ 1, 23],
       [ 2,  3],
       [21, 32]])