# Joshua Chavez
## Week 12 -   4/2/24 
### Python numpy creating,processing transporting arrays 

In [1]:
import numpy as np

In [3]:
arr_2d = np.arange(1,9).reshape(2,4)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr_3d = np.arange(1,9).reshape(2,2,2)
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [5]:
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# pass -1 as the value, and numpy will calc this number for you.
arr_2d = np.arange(1,9).reshape(2,-1)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
arr_xd = np.arange(1,1001).reshape(5,5,5,2,-1)
arr_xd

array([[[[[   1,    2,    3,    4],
          [   5,    6,    7,    8]],

         [[   9,   10,   11,   12],
          [  13,   14,   15,   16]],

         [[  17,   18,   19,   20],
          [  21,   22,   23,   24]],

         [[  25,   26,   27,   28],
          [  29,   30,   31,   32]],

         [[  33,   34,   35,   36],
          [  37,   38,   39,   40]]],


        [[[  41,   42,   43,   44],
          [  45,   46,   47,   48]],

         [[  49,   50,   51,   52],
          [  53,   54,   55,   56]],

         [[  57,   58,   59,   60],
          [  61,   62,   63,   64]],

         [[  65,   66,   67,   68],
          [  69,   70,   71,   72]],

         [[  73,   74,   75,   76],
          [  77,   78,   79,   80]]],


        [[[  81,   82,   83,   84],
          [  85,   86,   87,   88]],

         [[  89,   90,   91,   92],
          [  93,   94,   95,   96]],

         [[  97,   98,   99,  100],
          [ 101,  102,  103,  104]],

         [[ 105,  106,  107,  108]

In [33]:
arr_xd.shape

(5, 5, 5, 2, 4)

In [34]:
arr_2d.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
#Iterating Arrays
arr_1d = arr_2d.reshape(-1)
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
for n in arr_1d:
    print(n,end=" ")

1 2 3 4 5 6 7 8 

In [39]:
#2D
for n in arr_2d:
    print(n,end=" ")

[1 2 3 4] [5 6 7 8] 

In [41]:
for n in arr_2d:
    for x in n:
        print(x,end=" ")

1 2 3 4 5 6 7 8 

In [43]:
#3D
for arr2 in arr_3d:
    for arr in arr2:
        for n in arr:
              print(n,end=" ")
            

1 2 3 4 5 6 7 8 

In [44]:
#nditer iterates on each scaler element in the np array
for n in np.nditer(arr_3d):
    print(n,end=' ')

1 2 3 4 5 6 7 8 

In [46]:
#mulitidimensional index iteator
# ndenumerate()

In [47]:
for i,n in np.ndenumerate(arr_1d):
    print(i,n)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8


In [48]:
for i,n in np.ndenumerate(arr_2d):
    print(i,n)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [49]:
for i,n in np.ndenumerate(arr_3d):
    print(i,n)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


In [50]:
arr_3d[1,1,0]

7

In [51]:
arr_3d.shape

(2, 2, 2)

In [52]:
# operations *,+,-,/
arr_2d*arr_2d

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [53]:
arr_2d+arr_2d

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [57]:
#.t same as self.transpose() , expect that self if self.ndim < 2d
#returns the transpose of the matrix
#transpose reversee or permute the axes if an array; returnes the modfied array 
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
arr_2d.shape

(2, 4)

In [62]:
arr_2d.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [64]:
t.shape

NameError: name 't' is not defined

In [65]:
arr

array([7, 8])

In [66]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
t = arr_2d.T
t

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [68]:
arr_2d.T
t

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [69]:
arr_2d[:3]= 100
arr_2d

array([[100, 100, 100, 100],
       [100, 100, 100, 100]])

In [71]:
t[:,-1]= 25
t

array([[100,  25],
       [100,  25],
       [100,  25],
       [100,  25]])

In [73]:
arr_3d = np.arange(1, 21).reshape(-1, 5, 4)
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]])

In [74]:
arr_3d.T

array([[[ 1],
        [ 5],
        [ 9],
        [13],
        [17]],

       [[ 2],
        [ 6],
        [10],
        [14],
        [18]],

       [[ 3],
        [ 7],
        [11],
        [15],
        [19]],

       [[ 4],
        [ 8],
        [12],
        [16],
        [20]]])

In [75]:
arr_3d.T.shape

(4, 5, 1)

In [78]:
#transpose
arr_2d = np.arange(1,7).reshape(2,3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
np.transpose(arr_2d)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [81]:
arr_3d = np.arange(20).reshape(2,5,2)
arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [82]:
arr_3d.T

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [83]:
np.transpose(arr_3d)

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [84]:
np.transpose(arr_3d).shape

(2, 5, 2)

In [86]:
arr_3d.transpose((0,2,1))

array([[[ 0,  2,  4,  6,  8],
        [ 1,  3,  5,  7,  9]],

       [[10, 12, 14, 16, 18],
        [11, 13, 15, 17, 19]]])

In [87]:
arr_3d.transpose((0,2,1)).shape

(2, 2, 5)

In [88]:
arr_3d.transpose((0,2,1)).shape[0]

2

In [89]:
arr_3d.transpose((0,2,1)).shape[1]

2

In [91]:
arr_3d.transpose((0,2,1)).shape[2]

5

In [92]:
arr_3d.transpose((2,0,1))

array([[[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]],

       [[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]]])

In [93]:
#swapaxes
arr_3d = np.arange(24).reshape(2,3,4)
arr_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [94]:
arr_3d.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [95]:
arr_3d.swapaxes(0,1).shape

(3, 2, 4)

In [96]:
#4,3,2
arr_3d.swapaxes(0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])