# Joshua Chavez
## Week 12 -   4/4/24 
### Python numpy creating, universal functions 

In [1]:
#Universial function is a powerful tool
# For preforming mathmatical operations on NumPy arrays, ndarray
# this makes them much fater for looping over
#tthe elements of an array and preforming the operation manualy 
import numpy as np

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
#sqrt
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [3]:
#exp()

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [6]:
#randn - generates standard normal distribution sample

arr = np.random.randn(10)
print(arr)



[ 0.3899835   0.32007655  0.87401552  0.52146561  0.01332073 -2.15202977
 -1.0684352  -2.16220173  0.19000627 -0.00981257]


In [8]:
arr2  = np.random.randn(10)

In [9]:
arrr = (arr,arr2)

In [10]:
arrr

(array([ 0.3899835 ,  0.32007655,  0.87401552,  0.52146561,  0.01332073,
        -2.15202977, -1.0684352 , -2.16220173,  0.19000627, -0.00981257]),
 array([ 1.89605633, -0.16923401,  0.09101854, -0.13279237, -0.07347187,
         1.11319621,  1.08332206,  0.67733859, -0.45412637,  0.00599131]))

In [11]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
arr1 = np.random.randn(10)
print(arr1)


[ 0.93172137 -0.39295425  0.66212228 -0.3204873  -0.45229741  1.9655246
  1.22117002 -0.45727812  0.12277719  0.0634576 ]


In [14]:
np.add(arr1,arr2)

array([ 2.8277777 , -0.56218826,  0.75314082, -0.45327967, -0.52576927,
        3.07872081,  2.30449208,  0.22006047, -0.33134919,  0.06944891])

In [15]:
#array filtering
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
arr>4

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [18]:
#where
# replace values of an array usimg where
#return elemnts chossen from x or y depending on condtion
np.where(arr <4 ,arr, 0)

array([[0, 1, 2],
       [3, 0, 0],
       [0, 0, 0]])

In [19]:
np.where(arr >4 ,arr, 0)

array([[0, 0, 0],
       [0, 0, 5],
       [6, 7, 8]])

In [22]:
from numpy.random import randn
arr = randn(3,3)
arr

array([[ 1.20935436, -0.0151125 ,  1.52207944],
       [ 1.75652849, -0.60452191,  0.36130955],
       [ 0.52063004,  0.06974479,  0.72748649]])

In [23]:
np.where(arr<0,0,arr)

array([[1.20935436, 0.        , 1.52207944],
       [1.75652849, 0.        , 0.36130955],
       [0.52063004, 0.06974479, 0.72748649]])

In [24]:
np.where([True,False,True,False],1,0)

array([1, 0, 1, 0])

In [26]:
sample_bool_arr= [True,False]
arr_bool = np.random.choice(sample_bool_arr, size=10)
sample_bool_arr

[True, False]

In [30]:
sample_bool_arr= [True,False]
arr_bool = np.random.choice(sample_bool_arr, size=10)
arr_bool

array([ True,  True,  True,  True, False, False,  True,  True, False,
        True])

In [31]:
np.where(arr_bool,arr1,arr2)

array([ 0.93172137, -0.39295425,  0.66212228, -0.3204873 , -0.07347187,
        1.11319621,  1.22117002, -0.45727812, -0.45412637,  0.0634576 ])

In [35]:
result = [r1 if c else r2 for r1, r2, c in zip(arr1, arr2, arr_bool)]
result

[0.9317213733741515,
 -0.3929542547801258,
 0.6621222773185003,
 -0.3204872984716124,
 -0.07347186728605953,
 1.1131962097190011,
 1.2211700221068027,
 -0.4572781198825814,
 -0.4541263739464074,
 0.06345759755939004]

In [38]:
#useing where with 2-D arrray 
 # Create arr1 and arr2
arr1 = np.arange(1, 5).reshape(2, 2)
arr2 = np.arange(5, 9).reshape(2, 2)

# Create arr_bool
arr_bool = np.array([np.random.choice(sample_bool_arr, size=2), np.random.choice(sample_bool_arr, size=2)])
arr_bool

array([[ True, False],
       [ True, False]])

In [39]:
arr1

array([[1, 2],
       [3, 4]])

In [40]:
arr2

array([[5, 6],
       [7, 8]])

In [42]:
arr_bool = np.random.choice (sample_bool_arr, size =4).reshape(2,2)
arr_bool

array([[ True, False],
       [False, False]])

In [43]:
np.where(arr_bool,arr1,arr2)

array([[1, 6],
       [7, 8]])

In [48]:
#any
arr_bool.any()

True

In [49]:
#all

In [50]:
arr_bool.all()

False

In [53]:
#unique()
fruits= np.array(["apple",'cherry','cherry','apple', 'banana'])
np.unique(fruits)

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [55]:
fruits = ['apple', 'cherry', 'grape']
array_to_check = np.array(['apple', 'banana', 'cherry', 'orange'])

result = np.in1d(array_to_check, fruits)
print(result)


[ True False  True False]


In [56]:
arr

array([[ 1.20935436, -0.0151125 ,  1.52207944],
       [ 1.75652849, -0.60452191,  0.36130955],
       [ 0.52063004,  0.06974479,  0.72748649]])

In [58]:
arr.sum()

5.547498756765802

In [59]:
arr.sum(0)

array([ 3.48651289, -0.54988961,  2.61087548])

In [60]:
arr.sum(1)

array([2.7163213 , 1.51331613, 1.31786133])

In [61]:
np.mean(arr,axis= 1)

array([0.90544043, 0.50443871, 0.43928711])

In [62]:
arr.var()

0.5274018411156265

In [63]:
arr.std()

0.7262243738099311

In [66]:
arr = np.array([2,2,32,34,23,4,2,2,3,4,34,1,3,7])
arr.sort()

In [67]:
arr

array([ 1,  2,  2,  2,  2,  3,  3,  4,  4,  7, 23, 32, 34, 34])

In [71]:
#Random - Diffrent random [0,0,01]
np.random.randint(10,50)

23

In [73]:

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2))
print(arr)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
